honeys_place.settings:
  type: config_object
  label: 'Honeys Place Settings'
  mapping:
    honeys_place_api_endpoint:
      type: text
      label: 'REST Endpoint'
    honeys_place_api_username:
      type: text
      label: 'API Username'
    honeys_place_api_password:
      type: text
      label: 'API Password'
    honeys_place_api_use_sandbox:
      type: integer
      label: 'Sandbox Mode'
